blank_issues_enabled: false
contact_links:
  - name: 📚 Docs
    url: https://github.com/BetaHuhn/ackee-report/tree/master#-get-started
    about: Checkout ackee-reports's documentation
  - name: 🚀 Feature Request
    url: https://github.com/BetaHuhn/ackee-report/discussions/new?category=ideas
    about: Share ideas for new features
  - name: ❓ Ask a Question
    url: https://github.com/BetaHuhn/ackee-report/discussions/new?category=q-a
    about: Ask the community for help